export const environment = {
    name: 'dev',
    production: false,
    m2AppName: 'ScanDis',
    m2AppId: 'b1117f51-71d6-43f1-8acc-ffcdbd18316c',
    m2AppVersion: 'x.x',
    m2Url: 'https://www.mcgregor.io:9500',
    m2SessionTimeToLive: 20,
    m2SpinnerUrl: 'assets/images/wheel-white.svg',
    m2SpinnerWidth: 30,
    m2ButtonMinWidth: '180px',
    m2WebsiteUrl: 'http://outside.mcgegor.io',
    m2WebProxyPort: 3001,
    m2InfoUrl: null,
    m2ConfirmUrl: null,
    m2PostListImageUrl: null,
    stripePublishableKey: 'pk_test_2ub2SvNkrXpT9u2gKNoUYr1R',
    googleApiKey: 'AIzaSyA8KexBx7KwxEUikqfvUg0T4GTAmjIZcaI',
    plaidPublicKey: '817f602baf5a09feeb8f67f38ef94e',
    plaidEnv: 'sandbox',
    seedNodeHost: 'seed.dispatchlabs.io:1975'
};
